using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

namespace TsukiVox.AudioPrototype.Editor
{
    public static class QuestUrpProjectSettings
    {
        private const string SettingsDirectory = "Assets/Settings/Rendering";
        private const string PipelineAssetPath = SettingsDirectory + "/TsukiVoxQuestURP.asset";
        private const string RendererAssetPath = SettingsDirectory + "/TsukiVoxQuestRenderer.asset";
        private const string GlobalSettingsAssetPath = SettingsDirectory + "/UniversalRenderPipelineGlobalSettings.asset";
        private const string DefaultVolumeProfileAssetPath = SettingsDirectory + "/DefaultVolumeProfile.asset";
        private const string DefaultRendererTemplatePath =
            "Packages/com.unity.render-pipelines.universal/Runtime/Data/UniversalRendererData.asset";

        [InitializeOnLoadMethod]
        private static void ScheduleConfiguration()
        {
            EditorApplication.delayCall += ConfigureAfterReload;
        }

        private static void ConfigureAfterReload()
        {
            if (!EditorApplication.isPlayingOrWillChangePlaymode)
            {
                EnsureConfigured();
            }
        }

        [MenuItem("TsukiVox/Configure Quest URP")]
        public static void ConfigureFromMenu()
        {
            EnsureConfigured(true);
        }

        public static void EnsureConfigured(bool logResult = false)
        {
            Directory.CreateDirectory(SettingsDirectory);
            OrganizeAutoGeneratedAssets();

            var rendererData = LoadOrCreateRendererData();
            ConfigureRenderer(rendererData);

            var pipelineAsset = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(PipelineAssetPath);
            if (pipelineAsset == null)
            {
                pipelineAsset = UniversalRenderPipelineAsset.Create(rendererData);
                pipelineAsset.name = "TsukiVox Quest URP";
                AssetDatabase.CreateAsset(pipelineAsset, PipelineAssetPath);
            }

            BindRenderer(pipelineAsset, rendererData);
            ConfigurePipeline(pipelineAsset);
            AssignPipeline(pipelineAsset);
            PlayerSettings.colorSpace = ColorSpace.Linear;

            EditorUtility.SetDirty(rendererData);
            EditorUtility.SetDirty(pipelineAsset);
            AssetDatabase.SaveAssets();

            if (logResult)
            {
                Debug.Log($"[TsukiVox URP] Configured Quest renderer at {PipelineAssetPath}.");
            }
        }

        private static UniversalRendererData LoadOrCreateRendererData()
        {
            var rendererData = AssetDatabase.LoadAssetAtPath<UniversalRendererData>(RendererAssetPath);
            if (rendererData != null)
            {
                return rendererData;
            }

            if (!AssetDatabase.CopyAsset(DefaultRendererTemplatePath, RendererAssetPath))
            {
                rendererData = ScriptableObject.CreateInstance<UniversalRendererData>();
                AssetDatabase.CreateAsset(rendererData, RendererAssetPath);
                return rendererData;
            }

            AssetDatabase.ImportAsset(RendererAssetPath, ImportAssetOptions.ForceSynchronousImport);
            return AssetDatabase.LoadAssetAtPath<UniversalRendererData>(RendererAssetPath);
        }

        private static void ConfigureRenderer(UniversalRendererData rendererData)
        {
            rendererData.renderingMode = RenderingMode.Forward;
            rendererData.depthPrimingMode = DepthPrimingMode.Disabled;
            rendererData.copyDepthMode = CopyDepthMode.AfterTransparents;
            rendererData.depthAttachmentFormat = DepthFormat.Default;
            rendererData.depthTextureFormat = DepthFormat.Default;
            rendererData.accurateGbufferNormals = false;
            rendererData.intermediateTextureMode = IntermediateTextureMode.Auto;
            rendererData.shadowTransparentReceive = false;
            rendererData.tileOnlyMode = false;
        }

        private static void BindRenderer(UniversalRenderPipelineAsset pipelineAsset, UniversalRendererData rendererData)
        {
            var serialized = new SerializedObject(pipelineAsset);
            var rendererList = serialized.FindProperty("m_RendererDataList");
            rendererList.arraySize = 1;
            rendererList.GetArrayElementAtIndex(0).objectReferenceValue = rendererData;
            serialized.FindProperty("m_DefaultRendererIndex").intValue = 0;
            serialized.ApplyModifiedPropertiesWithoutUndo();
        }

        private static void ConfigurePipeline(UniversalRenderPipelineAsset pipelineAsset)
        {
            pipelineAsset.supportsCameraDepthTexture = false;
            pipelineAsset.supportsCameraOpaqueTexture = false;
            pipelineAsset.supportsHDR = true;
            pipelineAsset.hdrColorBufferPrecision = HDRColorBufferPrecision._32Bits;
            pipelineAsset.msaaSampleCount = 4;
            pipelineAsset.renderScale = 1f;
            pipelineAsset.maxAdditionalLightsCount = 4;
            pipelineAsset.mainLightShadowmapResolution = 1024;
            pipelineAsset.additionalLightsShadowmapResolution = 512;
            pipelineAsset.shadowDistance = 12f;
            pipelineAsset.shadowCascadeCount = 1;
            pipelineAsset.shadowDepthBias = 1f;
            pipelineAsset.shadowNormalBias = 1f;
            pipelineAsset.useSRPBatcher = true;

            var serialized = new SerializedObject(pipelineAsset);
            SetInt(serialized, "m_MainLightRenderingMode", (int)LightRenderingMode.PerPixel);
            SetBool(serialized, "m_MainLightShadowsSupported", false);
            SetInt(serialized, "m_AdditionalLightsRenderingMode", (int)LightRenderingMode.PerPixel);
            SetBool(serialized, "m_AdditionalLightShadowsSupported", true);
            SetBool(serialized, "m_AnyShadowsSupported", true);
            SetBool(serialized, "m_SoftShadowsSupported", true);
            SetInt(serialized, "m_SoftShadowQuality", (int)SoftShadowQuality.Low);
            SetInt(serialized, "m_AdditionalLightsShadowResolutionTierLow", 256);
            SetInt(serialized, "m_AdditionalLightsShadowResolutionTierMedium", 512);
            SetInt(serialized, "m_AdditionalLightsShadowResolutionTierHigh", 512);
            SetBool(serialized, "m_SupportsTerrainHoles", false);
            SetBool(serialized, "m_SupportsLightCookies", false);
            SetBool(serialized, "m_SupportsLightLayers", false);
            SetBool(serialized, "m_SupportDataDrivenLensFlare", false);
            SetBool(serialized, "m_SupportScreenSpaceLensFlare", false);
            SetBool(serialized, "m_UseAdaptivePerformance", false);
            SetBool(serialized, "m_EnableLODCrossFade", false);
            SetBool(serialized, "m_ReflectionProbeAtlas", false);
            serialized.ApplyModifiedPropertiesWithoutUndo();
        }

        private static void OrganizeAutoGeneratedAssets()
        {
            MoveAssetIfPresent("Assets/UniversalRenderPipelineGlobalSettings.asset", GlobalSettingsAssetPath);
            MoveAssetIfPresent("Assets/DefaultVolumeProfile.asset", DefaultVolumeProfileAssetPath);
        }

        private static void MoveAssetIfPresent(string sourcePath, string destinationPath)
        {
            if (AssetDatabase.LoadMainAssetAtPath(sourcePath) == null ||
                AssetDatabase.LoadMainAssetAtPath(destinationPath) != null)
            {
                return;
            }

            var error = AssetDatabase.MoveAsset(sourcePath, destinationPath);
            if (!string.IsNullOrEmpty(error))
            {
                Debug.LogWarning($"[TsukiVox URP] Could not move {sourcePath}: {error}");
            }
        }

        private static void AssignPipeline(RenderPipelineAsset pipelineAsset)
        {
            GraphicsSettings.defaultRenderPipeline = pipelineAsset;

            var originalQuality = QualitySettings.GetQualityLevel();
            for (var index = 0; index < QualitySettings.names.Length; index += 1)
            {
                QualitySettings.SetQualityLevel(index, false);
                QualitySettings.renderPipeline = pipelineAsset;
            }

            QualitySettings.SetQualityLevel(originalQuality, false);
        }

        private static void SetBool(SerializedObject serialized, string propertyName, bool value)
        {
            var property = serialized.FindProperty(propertyName);
            if (property != null)
            {
                property.boolValue = value;
            }
        }

        private static void SetInt(SerializedObject serialized, string propertyName, int value)
        {
            var property = serialized.FindProperty(propertyName);
            if (property != null)
            {
                property.intValue = value;
            }
        }
    }
}
